// <auto-generated />
using System;
using AdminPortalV8.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminPortalV8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240327040310_update_table_structure_3")]
    partial class update_table_structure_3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PvId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("StartActiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("IdentityRole", (string)null);
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool?>("FirstPasswordReset")
                        .HasColumnType("bit");

                    b.Property<bool?>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("cid")
                        .HasColumnType("int");

                    b.Property<string>("referId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityAccessLevel", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityAccessLevel");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityAccessLevelDetail", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("IdentityAccessLevelPvid")
                        .HasColumnType("bigint");

                    b.Property<long>("IdentityModulePvid")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityAccessLevelDetail");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityAccessLevelExclusive", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<bool>("Accessible")
                        .HasColumnType("bit");

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("IdentityUserPvid")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityAccessLevelExclusive");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityModule", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityModule");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityModuleOrganize", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("IdentityModulePvid")
                        .HasColumnType("bigint");

                    b.Property<string>("PermissionKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityModuleOrganize");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityRoleAccess", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("GrantedByIdentityUserPvid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("GrantedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("IdentityAccessLevelPvid")
                        .HasColumnType("bigint");

                    b.Property<long>("IdentityModulePvid")
                        .HasColumnType("bigint");

                    b.Property<long>("IdentityRolePvid")
                        .HasColumnType("bigint");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityRoleAccess");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.IdentityUserProfiles", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("IdentityUserPvid")
                        .HasColumnType("bigint");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityUserProfiles");
                });

            modelBuilder.Entity("AdminPortalV8.Data.ExtendedIdentity.UserPasswordsHistory", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PasswordDate1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate6")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PasswordDate7")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserPasswordHistory");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.IdentityRoleProfiles", b =>
                {
                    b.Property<long>("Pvid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Pvid"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<long>("IdentityRolePvid")
                        .HasColumnType("bigint");

                    b.Property<long>("IdentityUserPvid")
                        .HasColumnType("bigint");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pvid");

                    b.ToTable("IdentityRoleProfiles");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.InterestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InterestTypes");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguagePreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("NRIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Race")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Residential")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("referID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.AdditionalRequest", b =>
                {
                    b.Property<int>("additionalrequest_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("additionalrequest_id"));

                    b.Property<DateTime>("delivery_endtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("delivery_starttime")
                        .HasColumnType("datetime2");

                    b.Property<int>("robot_id")
                        .HasColumnType("int");

                    b.HasKey("additionalrequest_id");

                    b.ToTable("additionalrequest");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.AdditionalRequestDetail", b =>
                {
                    b.Property<int>("requestdetail_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("requestdetail_id"));

                    b.Property<int>("additionalrequest_id")
                        .HasColumnType("int");

                    b.Property<int>("item_qty")
                        .HasColumnType("int");

                    b.Property<int>("item_type")
                        .HasColumnType("int");

                    b.Property<int>("table_no")
                        .HasColumnType("int");

                    b.Property<int>("tag_id")
                        .HasColumnType("int");

                    b.HasKey("requestdetail_id");

                    b.HasIndex("additionalrequest_id");

                    b.ToTable("additionalrequestdetail");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.Anchor", b =>
                {
                    b.Property<int>("anchor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("anchor_id"));

                    b.Property<double>("X_Axis")
                        .HasColumnType("float");

                    b.Property<double>("Y_Axis")
                        .HasColumnType("float");

                    b.Property<string>("anchor_address")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ismain_anchor")
                        .HasColumnType("int");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.HasKey("anchor_id");

                    b.ToTable("anchor");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.Order", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<DateTime>("delivery_endtime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("delivery_starttime")
                        .HasColumnType("datetime2");

                    b.Property<int>("robot_id")
                        .HasColumnType("int");

                    b.Property<int>("table_no")
                        .HasColumnType("int");

                    b.Property<int>("tag_id")
                        .HasColumnType("int");

                    b.HasKey("order_id");

                    b.ToTable("order");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.Restaurant", b =>
                {
                    b.Property<int>("restaurant_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("restaurant_id"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<int>("manager")
                        .HasColumnType("int");

                    b.Property<string>("restaurant_address")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("restaurant_name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("restaurant_id");

                    b.ToTable("restaurant");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.Robot", b =>
                {
                    b.Property<int>("robot_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("robot_id"));

                    b.Property<int>("active")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<string>("robot_serialnum")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("robot_id");

                    b.ToTable("robot");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.TableCoordinate", b =>
                {
                    b.Property<int>("tablecoordinate_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tablecoordinate_id"));

                    b.Property<double>("point_1x")
                        .HasColumnType("float");

                    b.Property<double>("point_1y")
                        .HasColumnType("float");

                    b.Property<double>("point_2x")
                        .HasColumnType("float");

                    b.Property<double>("point_2y")
                        .HasColumnType("float");

                    b.Property<double>("point_3x")
                        .HasColumnType("float");

                    b.Property<double>("point_3y")
                        .HasColumnType("float");

                    b.Property<double>("point_4x")
                        .HasColumnType("float");

                    b.Property<double>("point_4y")
                        .HasColumnType("float");

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<int>("table_id")
                        .HasColumnType("int");

                    b.HasKey("tablecoordinate_id");

                    b.ToTable("tablecoordinate");
                });

            modelBuilder.Entity("AdminPortalV8.Entities.TagInfo", b =>
                {
                    b.Property<int>("tag_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tag_id"));

                    b.Property<int>("restaurant_id")
                        .HasColumnType("int");

                    b.Property<string>("tag_address")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("tag_id");

                    b.ToTable("taginfo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AdminPortalV8.Entities.AdditionalRequestDetail", b =>
                {
                    b.HasOne("AdminPortalV8.Entities.AdditionalRequest", "additionalrequest")
                        .WithMany()
                        .HasForeignKey("additionalrequest_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("additionalrequest");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AdminPortalV8.Data.ExtendedIdentity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
