// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Aimodel
{
    public int ModelId { get; set; }

    public string Detection { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public virtual ICollection<CheckList> CheckLists { get; set; } = new List<CheckList>();
}