// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Building
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int NumberOfFloors { get; set; }

    public string ImageName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? LocationId { get; set; }

    public virtual Location Location { get; set; }
}