// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class CameraStatus
{
    //public int CamareStatusId { get; set; } 
    //public string Note { get; set; }
    //public string Status { get; set; }
    //public DateTime? StatusDate { get; set; }
    //public int? LocationCameraId { get; set; }
    //public string Description { get; set; }
    //public virtual Camera Camera { get; set; }

    //public int CameraStatusId { get; set; }

    //public int? LocationCameraId { get; set; }

    //public string Note { get; set; }

    //public string Description { get; set; }

    //public string Status { get; set; }

    //public DateTime? StatusDate { get; set; }

    //public int CameraStatusId { get; set; }

    //public string Note { get; set; }

    //public string Description { get; set; }

    //public string Status { get; set; }

    //public DateTime StatusDate { get; set; }

    //public string NotificationMethod { get; set; }

    //public int CameraId { get; set; }

    //public virtual Camera Camera { get; set; }

    public int CameraStatusId { get; set; }

    public int? CameraId { get; set; }

    public string Note { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? StatusDate { get; set; }

    public string NotificationMethod { get; set; }
}