// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPortalV8.Models.Epatrol;

[Table("CameraHealthResult")]
public class CameraHealthResult
{
    public int Id { get; set; }
    public int CameraId { get; set; }
    public string CameraName { get; set; }
    public string Status { get; set; }
    public string Result { get; set; }
    public DateTime Timestamp { get; set; }
    public string BlockName { get; set; }
    public string Level { get; set; }

    //public int Id { get; set; }

    //public int CameraId { get; set; }

    //public string CameraName { get; set; }

    //public string Result { get; set; }

    //public DateTime? Timestamp { get; set; }

    //public string Status { get; set; }

    //public string BlockName { get; set; }

    //public string Level { get; set; }

    //public virtual Camera Camera { get; set; }
}
