// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPortalV8.Models.Epatrol;

public partial class Camera
{
    public int CameraId { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Tailgatezone { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsActive { get; set; }

    public bool IsAutoDetectFire { get; set; }

    //public virtual ICollection<CameraStatus> CameraStatuses { get; set; } = new List<CameraStatus>();

    public virtual ICollection<CameraStatusNew> CameraStatusNews { get; set; } = new List<CameraStatusNew>();

    public virtual ICollection<CheckPoint> CheckPoints { get; set; } = new List<CheckPoint>();

    public virtual ICollection<CheckList> CheckLists { get; set; } = new List<CheckList>();

    public virtual ICollection<Camera_CheckList> CameraCheckLists { get; set; } = new List<Camera_CheckList>();

    public virtual ICollection<FireDetected> FireDetecteds{ get; set; } = new List<FireDetected>();

    public virtual ICollection<ScheduleCameraCheck> Schedules { get; set; } = new List<ScheduleCameraCheck>();

    public int? LocationId { get; set; }

    public virtual Location Location { get; set; }

    public byte[] CameraImage { get; set; }

    public string Coordinate { get; set; }
}
