// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPortalV8.Models.Epatrol;

[Table("Camera_CheckList")] // Ensure the table name matches your database
public class Camera_CheckList
{
    [Key]
    public int CameraCheckListId { get; set; } // Primary Key

    [ForeignKey("Camera")]
    public int CameraId { get; set; }

    [ForeignKey("CheckList")]
    public int CheckListId { get; set; }

    public TimeSpan? StartTime { get; set; }
    public TimeSpan? EndTime { get; set; }

    public virtual Camera Camera { get; set; }
    public virtual CheckList CheckList { get; set; }
}
