// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class CheckPoint
{
    public int CheckPointId { get; set; }

    public string CheckPointName { get; set; }

    public int? LocationId { get; set; }


    public virtual Location Location { get; set; }

    public virtual ICollection<RouteCheckPoint> RouteCheckPoints { get; set; } = new List<RouteCheckPoint>();

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();

    public virtual ICollection<CheckList> CheckLists { get; set; } = new List<CheckList>();
}