// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdminPortalV8.Models.Epatrol;

public partial class CheckList
{
    public int CheckListId { get; set; }

    public string CheckListName { get; set; }

    public string Model { get; set; }

    public string Type { get; set; }

    public int? ModelId { get; set; }

    public virtual Aimodel ModelNavigation { get; set; }

    public virtual ICollection<CheckPoint> CheckPoints { get; set; } = new List<CheckPoint>();

    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();
    public virtual ICollection<Camera_CheckList> CameraCheckLists { get; set; } = new List<Camera_CheckList>();

}