// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class FireDetected
{
    public int Id { get; set; }

    public int CameraId { get; set; }

    public string VideoPath { get; set; }

    public byte[] VideoBin { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string Type { get; set; }
    public virtual Camera Camera { get; set; }
}