// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Guard
{
    public int GuardId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Patrol> Patrols { get; set; } = new List<Patrol>();
}