// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AdminPortalV8.Models.Epatrol;

public partial class LocationCamera
{

    public virtual ICollection<CameraStatus> CameraStatuses { get; set; } = new List<CameraStatus>();

    public int LocationCameraId { get; set; }

    public int LocationId { get; set; }

    public string Name { get; set; }

    public string RtspUrl { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsAutoDetectFire { get; set; }

    [JsonIgnore]
    public virtual Location Location { get; set; }

}