// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AdminPortalV8.Models.Epatrol;

public partial class Location
{
    public virtual ICollection<CheckPoint> CheckPoints { get; set; } = new List<CheckPoint>();

    [JsonIgnore]
    public virtual ICollection<LocationCamera> LocationCameras { get; set; } = new List<LocationCamera>();

    public int LocationId { get; set; }

    public string Name { get; set; }

    public string Level { get; set; }

    public byte[] Image { get; set; }

    //public virtual ICollection<LocationCamera> LocationCameras { get; set; } = new List<LocationCamera>();

    [JsonIgnore]
    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();
}