// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models;

public partial class Notification
{
    public int Id { get; set; }

    public int? CameraId { get; set; }

    public string Device { get; set; }

    public string Type { get; set; }

    public string Location { get; set; }

    public DateTime? Timestamp { get; set; }

    public string Note { get; set; }

    public bool Clear { get; set; }

    public bool Acknowledge { get; set; }
}