// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class PatrolType
{
    public int PatrolTypeId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();
}