// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Patrol
{
    public int PatrolId { get; set; }

    public DateOnly? Date { get; set; }

    public TimeOnly? Time { get; set; }

    public string Status { get; set; }

    public int? RouteId { get; set; }

    public string Note { get; set; }

    public string CheckListName { get; set; }

    public string CheckPointName { get; set; }

    public string Link { get; set; }

    public string GuardName { get; set; }


    //public int? GuardId { get; set; }

    //public virtual Guard Guard { get; set; }

    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    public virtual Route Route { get; set; }

    //new
    public byte[] VideoLink { get; set; }
}