// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Report
{
    public int ReportId { get; set; }

    public DateOnly? Date { get; set; }

    public int? PatrolId { get; set; }

    public virtual Patrol Patrol { get; set; }
}