// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class RouteCheckPoint
{
    public int RouteId { get; set; }

    public int CheckPointId { get; set; }

    public string CameraId { get; set; }

    public string Coordinate { get; set; }

    public virtual CheckPoint CheckPoint { get; set; }

    public virtual Route Route { get; set; }
}