// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class RouteSchedule
{
    public int RouteId { get; set; }

    public int ScheduleId { get; set; }

    public virtual Route Route { get; set; }

    public virtual Schedule Schedule { get; set; }
}