// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Route
{
    public int RouteId { get; set; }

    public string RouteName { get; set; }

    public int? CheckPointId { get; set; }

    public int? ScheduleId { get; set; }

    public int? PatrolTypeId { get; set; }

    public byte[] Image { get; set; }

    public int? Duration { get; set; }

    public bool AutoPatrol { get; set; }

    public int? SleepTime { get; set; }

    public virtual CheckPoint CheckPoint { get; set; }

    public virtual PatrolType PatrolType { get; set; }

    public virtual ICollection<Patrol> Patrols { get; set; } = new List<Patrol>();

    public virtual ICollection<RouteCheckPoint> RouteCheckPoints { get; set; } = new List<RouteCheckPoint>();

    public virtual Schedule Schedule { get; set; }

    public virtual ICollection<Schedule> Schedules { get; set; } = new List<Schedule>();

    public virtual ICollection<RouteSchedule> RouteSchedules { get; set; } = new List<RouteSchedule>();
}