// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class Schedule
{
    public int ScheduleId { get; set; }

    public string ScheduleName { get; set; }

    public string Day { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public virtual ICollection<Route> Routes { get; set; } = new List<Route>();

    public virtual ICollection<Route> RoutesNavigation { get; set; } = new List<Route>();
    public virtual ICollection<RouteSchedule> RouteSchedules { get; set; } = new List<RouteSchedule>();

}