// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class ScheduleCameraCheck
{
    public int ScheduleId { get; set; }

    public string ScheduleName { get; set; }

    public string Day { get; set; }

    public TimeOnly StartTime { get; set; }

    public string NotificationMethod { get; set; }
    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();
}