// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models;

public partial class UserCameraSelection
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int CheckPointId { get; set; }

    public DateTime UpdatedAt { get; set; }
}