// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AdminPortalV8.Models.Epatrol;

public partial class VideoFile
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public byte[] Content { get; set; }

    public string ContentType { get; set; }
}